const purchaserDepartments = [
  'Assoc VC Human Resources',
  'Athletics',
  'Bradford',
  'Business Affairs',
  'Business Operations',
  'Chancellor',
  'Chief Financial Officer',
  'College of General Studies',
  'CSSD',
  'Dental Medicine',
  'Dietrich School of Arts and Sciences',
  'Education',
  'Educ-Univ Service Programs',
  'Executive Vice Chancellor',
  'Facilities Management',
  'General Counsel',
  'General University',
  'Greensburg',
  'GSPH',
  'GSPIA',
  'Honors College',
  'Information Sciences',
  'Johnstown',
  'Katz Grad School of Bus',
  'Law',
  'Libraries',
  'LRDC',
  'Medicine',
  'Nursing',
  'PCI',
  'Pharmacy',
  'Provost',
  'Research Conduct and Compliance',
  'Secretary of the Board of Trustees',
  'SHRS',
  'Social Work',
  'SOM Division Administration',
  'Student Affairs',
  'SVC Health Sciences',
  'Swanson School of Engineering',
  'Titusville',
  'UCIS',
  'UCSUR',
  'VC Institutional Advancement',
  'WPIC'
];

const purchaseTypes = [
  'Facility Alterations',
 'Facility Operating Costs',
 'Insurance',
 'Library Acquisitions',
 'Mail',
 'Printing/Publishing',
 'Professional Memberships',
 'Professional Services',
 'Purchases for Resale',
 'Routine Maintenance',
 'Space Rental',
 'Supplies/Equipment',
 'Telephone',
 'Utilities'
];

module.exports = {
  purchaserDepartments,
  purchaseTypes
};
