const purchaserDepartments = [
  'Athletics',
  'Bradford Campus',
  'Business Affairs',
  'Business Operations',
  'Chancellor',
  'Chief Financial Officer',
  'College of General Studies',
  'Computing Services & Systems Development',
  'Education-University Service Programs',
  'Facilities Management',
  'General University',
  'Graduate School of Public & International Affairs',
  'Graduate School of Public Health',
  'Greensburg Campus',
  'Honors College',
  'Johnstown Campus',
  'Katz Graduate School of Business',
  'Kenneth P. Dietrich School of Arts and Sciences',
  'Learning Research & Development Center',
  'Libraries',
  'Office of University Counsel',
  'School of Computing and Information',
  'School of Dental Medicine',
  'School of Education',
  'School of Health & Rehabilitation Sciences',
  'School of Law',
  'School of Medicine',
  'School of Medicine Division Administration',
  'School of Nursing',
  'School of Pharmacy',
  'School of Social Work',
  'Secretary of the Board of Trustees',
  'Sr V C and Provost',
  'Sr V C Business and Operations',
  'Sr V C Health Sciences',
  'Sr V C Research',
  'Student Affairs',
  'Swanson School of Engineering',
  'Titusville Campus',
  'University Center for International Studies',
  'UPMC Hillman Cancer Center',
  'V C Human Resources',
  'V C Institutional Advancement',
  'Western Psychiatric Institute and Clinic'
];

// For backwards compatibility with older reports
const purchaserDepartmentAliases = {
  'Assoc VC Human Resources': 'V C Human Resources',
  'Associate Vice Chancellor, Human Resources': 'V C Human Resources',
  'Bradford': 'Bradford Campus',
  'College of Gen Studies': 'College of General Studies',
  'CSSD': 'Computing Services & Systems Development',
  'Dental Medicine': 'School of Dental Medicine',
  'Education': 'School of Education',
  'Educ-Univ Service Programs': 'Education-University Service Programs',
  'Executive Vice Chancellor': 'Chancellor',
  'GSPH': 'Graduate School of Public Health',
  'GSPIA': 'Graduate School of Public & International Affairs',
  'General Counsel': 'Office of University Counsel',
  'Greensburg': 'Greensburg Campus',
  'Information Sciences': 'School of Computing and Information',
  'Johnstown': 'Johnstown Campus',
  'Katz Grad School of Bus': 'Katz Graduate School of Business',
  'Kenneth P. Dietrich School of': 'Kenneth P. Dietrich School of Arts and Sciences',
  'Law': 'School of Law',
  'LRDC': 'Learning Research & Development Center',
  'Medicine': 'School of Medicine',
  'Nursing': 'School of Nursing',
  'Office of the Chief Financial': 'Chief Financial Officer',
  'PCI': 'UPMC Hillman Cancer Center',
  'Pharmacy': 'School of Pharmacy',
  'Provost': 'Sr V C and Provost',
  'Research Conduct and Complianc': 'Sr V C Research',
  'Research Conduct and Compliance': 'Sr V C Research',
  'School of Health & Rehabilition Sciences': 'School of Health & Rehabilitation Sciences',
  'School of Information Sciences': 'School of Computing and Information',
  'Secretary of the Univ': 'Secretary of the Board of Trustees',
  'Senior Vice Chancellor and Provost': 'Sr V C and Provost',
  'Senior Vice Chancellor, Business and Operations': 'Business Operations',
  'Senior Vice Chancellor, Health Sciences': 'Sr V C Health Sciences',
  'SHRS': 'School of Health & Rehabilitation Sciences',
  'Social Work': 'School of Social Work',
  'SOM Division Administration': 'School of Medicine Division Administration',
  'SVC Health Sciences': 'Sr V C Health Sciences',
  'Titusville': 'Titusville Campus',
  'University Center for Social & Urban Research': 'Sr V C Research',
  'UCIS': 'University Center for International Studies',
  'UCSUR': 'Sr V C Research',
  'University of Pittsburgh Applied Research Center': 'Sr V C Research',
  'University of Pittsburgh Cancer Institute': 'UPMC Hillman Cancer Center',
  'VC Institut Advancement': 'V C Institutional Advancement',
  'Vice Chancellor, Human Resources': 'V C Human Resources',
  'Vice Chancellor, Institutional Advancement': 'V C Institutional Advancement',
  'WPIC': 'Western Psychiatric Institute and Clinic'
};

const purchaseTypes = {
  6000: 'Supplies/Equipment',
  6400: 'Professional Services',
  6500: 'Library Acquisitions',
  6600: 'Telephone',
  6700: 'Mail',
  6800: 'Printing/Publishing',
  6900: 'Professional Memberships',
  7000: 'Utilities',
  7100: 'Routine Maintenance',
  7135: 'Facility Operating Costs',
  7140: 'Facility Alterations',
  7300: 'Space Rental',
  7400: 'Purchases for Resale',
  7700: 'Insurance'
};

module.exports = {
  purchaserDepartments,
  purchaserDepartmentAliases,
  purchaseTypes
};
