const purchaserDepartments = {
  1: 'Chancellor',
  2: 'SVC Engagement',
  3: 'SVC Research',
  5: 'Student Affairs',
  6: 'Dietrich School of Arts and Sciences',
  10: 'SVC and Provost',
  15: 'College of General Studies',
  20: 'Honors College',
  21: 'Katz Graduate School of Business',
  22: 'School of Education',
  23: 'Swanson School of Engineering',
  24: 'School of Law',
  25: 'Graduate School of Public & International Affairs',
  26: 'School of Social Work',
  30: 'SVC Health Sciences',
  31: 'School of Dental Medicine',
  32: 'School of Nursing',
  33: 'School of Pharmacy',
  34: 'Graduate School of Public Health',
  35: 'School of Medicine',
  39: 'School of Health & Rehabilitation Sciences',
  41: 'Johnstown Campus',
  42: 'Greensburg Campus',
  43: 'Titusville Campus',
  44: 'Bradford Campus',
  51: 'University Center for International Studies',
  54: 'Office of University Counsel',
  55: 'UPMC Hillman Cancer Center',
  56: 'SVC Philanthropic and Alumni Engagement',
  57: 'Education - University Service Programs',
  60: 'Libraries',
  61: 'Information Technology',
  67: 'Facilities Management',
  78: 'Learning Research & Development Center',
  79: 'Business Affairs',
  80: 'Athletics',
  81: 'University Center for Social & Urban Research',
  83: 'General University',
  85: 'School of Medicine Division Administration',
  86: 'SVC Business and Operations',
  87: 'Chief Financial Officer',
  89: 'Human Resources',
  90: 'Western Psychiatric Institute and Clinic',
  91: 'Planning, Design and Real Estate',
  92: 'Business and Auxiliary Services',
  93: 'Public Safety and Emergency Management',
  94: 'School of Computing and Information'
};

const purchaseTypes = {
  6000: 'Supplies/Equipment',
  6400: 'Professional Services',
  6500: 'Library Acquisitions',
  6600: 'Telephone',
  6700: 'Mail',
  6800: 'Printing/Publishing',
  6900: 'Professional Memberships',
  7000: 'Utilities',
  7100: 'Routine Maintenance',
  7135: 'Facility Operating Costs',
  7140: 'Facility Alterations',
  7300: 'Space Rental',
  7400: 'Purchases for Resale',
  7700: 'Insurance'
};

module.exports = {
  dataColumns: ['year', 'amount', 'vendor_number', 'vendor_name', 'vendor_address', 'purchaser_department', 'type'],
  dataYears: [2014, 2015, 2016, 2017, 2018, 2019, 2020],
  purchaserDepartments,
  purchaseTypes
};
